spring.application.name=tesis_proyecto

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


app.mail.from=onboarding@resend.dev
app.mail.from-name=Sistema de Seguridad

server.port=${PORT:8080}
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
jwt.secret=${JWT_SECRET:78037ad50a124c6e27f2bb9c4347bc212a04ef4f5c462bfec61f4fa8f652569d}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require